#!/usr/bin/dash
SRC=/mnt/ssd
DEST=conor/ssd
DATETIME=$(date "+%F_%T")
SERVER="charlie@shtanton.xyz"

rsync -aAHXv --delete --delete-excluded --ignore-errors --exclude-from=/home/charlie/data/backup_exclude --link-dest="../latest" "${SRC}/" "${SERVER}:${DEST}/${DATETIME}"
ssh $SERVER "update_latest ~/${DEST}/${DATETIME} ~/${DEST}/latest"
